"let g:pathogen_disabled = []
"call add(g:pathogen_disabled, 'youcompleteme')
"call add(g:pathogen_disabled, 'tagbar')
"execute pathogen#infect()

source ~/.vim/vundlerc.vim

set runtimepath+=~/.vim

source ~/.vim/basic.vim
source ~/.vim/filetypes.vim
"source ~/.vim/plugins_config.vim
source ~/.vim/extended.vim

try
    source ~/.vim/my_configs.vim
catch
endtry

