"let g:pathogen_disabled = []
"call add(g:pathogen_disabled, 'youcompleteme')
"call add(g:pathogen_disabled, 'tagbar')
"execute pathogen#infect()

source ~/.vim/vimrcs/vundlerc.vim

set runtimepath+=~/.vim

source ~/.vim/vimrcs/basic.vim
source ~/.vim/vimrcs/filetypes.vim
"source ~/.vim/vimrcs/plugins_config.vim
source ~/.vim/vimrcs/extended.vim

try
    source ~/.vim/vimrcs/my_configs.vim
catch
endtry

